### ISSUE TITLE
Change file change notification

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/oc.user#30]
Do not listen on all changes in /tmp but only on unix socket change 
For example

Event: rename on file /tmp/lastcmd.log
Event: change on file /tmp/lastcmd.log
Event: change on file /tmp/lastcmd.log
Event: rename on file /tmp/lastcmdenv.log
Event: change on file /tmp/lastcmdenv.log
Event: change on file /tmp/lastcmd.log
Event: change on file /tmp/lastcmd.log
Event: rename on file /tmp/firefox-esr.cmd.log
Event: change on file /tmp/firefox-esr.cmd.log
Event: rename on file /tmp/firefox-esr
Event: rename on file /tmp/firefox-esr
Event: change on file /tmp/firefox-esr.cmd.log
Event: change on file /tmp/lastcmd.log
Event: rename on file /tmp/firefox-esr.log
Event: rename on file /tmp/firefox-esr
Event: rename on file /tmp/Temp-458d8b29-9667-419e-8826-553fabbbe324
Event: rename on file /tmp/Temp-85b558a8-15c0-4b92-86ee-988906e8c5b9
Event: rename on file /tmp/firefox-esr

**Comment by kecsou** [comment]
Fixed with the new implementation
